---
title: GoAIA
timezone: UTC
collections:
  media:
    title: Media
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  camps:
    title: Camps
    output: false
  teams:
    title: Teams
    output: false
  events:
    title: Events
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    byLine: ''
    layout: pages
- scope:
    path: ''
    type: camps
  values:
    location: 
    start_date:
    end_date:
    event_id:
    layout: page
    address: 
    type:
- scope:
    path: ''
    type: teams
  values:
    level: 
    director:
    director_email:
    dates:
    type:
    layout: page
- scope:
    path: ''
    type: events
  values:
    location: 
    image:
    start_date:
    end_date:
    layout: page
    alt_url: 
    short_description:
    final_four:
include: ["_pages"]
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Celebrating the Induction to the Hall of Faith
url: 
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
sass:
  style: compressed